name: Build image
on:
  push:
    branches:
      # Spustí se pro všechny branche
      - "*"
    tags:
      # Spustí se pro všechny semver tagy typu v1.2.3
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Resolve release name
        id: release
        run: |
          RELEASE_NAME=""
          GITHUB_REF_STRIPPED=${GITHUB_REF#refs/}
          REF_NAME=${GITHUB_REF_STRIPPED##*/}
          REF_TYPE=${GITHUB_REF_STRIPPED%/*}

          if [[ "$REF_TYPE" == "heads" ]]; then
            if [[ "$REF_NAME" == "master" ]]; then
              RELEASE_NAME="${GITHUB_SHA}"
            else
              RELEASE_NAME="$REF_NAME"
            fi
          elif [[ "$REF_TYPE" == "tags" ]]; then
            # Odstraní prefix "v" → z v3.3.1 dostane 3.3.1
            RELEASE_NAME="${REF_NAME##v}"
          fi

          echo "Using $RELEASE_NAME as release name."
          echo "name=$RELEASE_NAME" >> $GITHUB_OUTPUT
      # setup docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # build docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/schizofreny/mlflow-docker/mlflow:${{ steps.release.outputs.name }}
