name: Docker Image CI

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jerray/publish-docker-action@master
        with:
          auto_tag: true
          repository: schizofreny/mlflow-docker/mlflow
          registry: docker.pkg.github.com
          username: schizofreny
          password: ${{ secrets.GITHUB_TOKEN }}
